// src/components/navbar.jsx
import { useState } from "react";
import { motion } from "framer-motion";

export default function Navbar(props) {
  const [isShown, setIsShown] = useState(false);
  const [imgURL, setImgURL] = useState("/burger.svg");
  const [isActive, setIsActive] = useState(false);

  window.onscroll = function () {
    scrollFunction();
  };

  function scrollFunction() {
    if (
      document.body.scrollTop > 420 ||
      document.documentElement.scrollTop > 420
    ) {
      document.getElementById("navbar").style.padding = "5px";
      document.getElementById("logo").style.height = "50px";
      document.getElementById("logo_text").style.padding = "8px";
      document.getElementById("burgerking_menu").style.padding = "8px";
      setIsShown(false);
    } else {
      document.getElementById("navbar").style.padding = "10px";
      document.getElementById("logo").style.height = "60px";
      document.getElementById("logo_text").style.padding = "12px";
      document.getElementById("burgerking_menu").style.padding = "12px";
    }
  }
  // function changeIcon(props) {
  //   setImgURL("/close.svg");
  // }

  const showMenu = () => {
    setIsShown((current) => !current);
  };

  return (
    <div className="p-3 ">
      <nav
        style={{
          borderBottomLeftRadius: isShown ? "0px" : "12px",
          borderBottomRightRadius: isShown ? "0px" : "12px",
        }}
        id="navbar"
        className="flex flex-row items-center p-5 rounded-t-xl bg-dark"
      >
        <div
          className="flex flex-row items-center gap-2 duration-300"
          id="logo"
        >
          <motion.div
            className="block"
            onClick={() => setIsActive(!isActive)}
            animate={{
              rotate: isActive ? 158.5 : 360,
            }}
          >
            <img
              src="/Logo-flat.svg"
              id="logo_img"
              className="items-center h-10 rounded-full bg-dark_light"
            />
          </motion.div>
          <button
            href="/"
            id="logo_text"
            className="p-3 text-xl font-semibold duration-100 rounded-lg hover:bg-dark_light hover:scale-110 active:scale-90"
          >
            User5522
          </button>
        </div>
        <div className="md:hidden">
          <div className="flex items-center">
            <button
              id="burgerking_menu"
              className="absolute p-3 text-xl duration-100 rounded-lg hover:bg-dark_light hover:scale-110 active:scale-90 right-10"
              onClick={() => {
                showMenu();
              }}
            >
              <img src={imgURL} />
            </button>
          </div>
        </div>
      </nav>
      {isShown && (
        <div className="flex flex-col items-center justify-center max-h-screen gap-5 pb-10 pl-10 pr-10 bg-dark rounded-b-xl min-w-screen ">
          <button
            href="/Vbot"
            className="w-full p-3 duration-200 bg-dark_light rounded-xl hover:scale-110 active:scale-90"
          >
            Vbot
          </button>
          <>
            <button className="w-full p-3 duration-200 bg-dark_light rounded-xl hover:scale-110 active:scale-90">
              404 page
            </button>
          </>
          <button
            href="/About"
            className="w-full p-3 duration-200 bg-dark_light rounded-xl hover:scale-110 active:scale-90"
          >
            About (unavailable)
          </button>
        </div>
      )}
    </div>

    /* {!isShown && (
        <div className="absolute flex flex-row items-center justify-center gap-5 right-10">
          <button className="w-full p-3 duration-200 hover:bg-dark_light rounded-xl hover:scale-110">
            Vbot
          </button>
          <button className="w-full p-3 duration-200 hover:bg-dark_light rounded-xl hover:scale-110">
            404
          </button>
          <button className="w-full p-3 duration-200 hover:bg-dark_light rounded-xl hover:scale-110">
            About
          </button>
        </div>
      )} */
  );
}

// src/lib/navbar.svelte
<script>
  import { onMount } from "svelte";

  onMount(() => {
    window.onscroll = function () {
      scrollFunction();
    };

    function scrollFunction() {
      if (
        document.body.scrollTop > 100 ||
        document.documentElement.scrollTop > 100
      ) {
        document.getElementById("padding").style.padding = "0px";
        document.getElementById("navbar").style.borderRadius = "0px";
        document.getElementById("navbar").classList.add("sm:bg-opacity-50");
        document.getElementById("navbar").classList.add("sm:backdrop-blur-md");
        document.getElementById("padding").style.transitionDuration = "400ms";
        document.getElementById("navbar").style.transitionDuration = "400ms";
      } else {
        document.getElementById("padding").style.padding = "12px";
        document.getElementById("navbar").style.borderRadius = "12px";
        document.getElementById("navbar").classList.remove("sm:bg-opacity-50");
        document
          .getElementById("navbar")
          .classList.remove("sm:backdrop-blur-md");
        document.getElementById("padding").style.transitionDuration = "400ms";
        document.getElementById("navbar").style.transitionDuration = "400ms";
      }
    }
  });
</script>

<div class="pb-28">
  <div
    id="padding"
    class="fixed top-0 z-50 flex w-full flex-col justify-center overflow-auto p-3 align-middle"
  >
    <div id="navbar" class="flex flex-row rounded-xl bg-dark p-4 shadow-lg">
      <div
        class="flex w-1/2 flex-row items-center gap-1 duration-300 sm:gap-2"
        id="logo"
      >
        <img
          src="/Logo_flat.svg"
          class="h-9 items-center rounded-full bg-dark_light bg-opacity-50 backdrop-blur-md delay-10000 duration-300 hover:rotate-180 sm:h-10"
          alt="logo"
        />
        <a href="/" class="text-white">
          <button
            id="logo_text"
            class="rounded-lg p-2 text-base font-bold duration-200 hover:scale-110 hover:bg-dark_light hover:bg-opacity-50 active:scale-90 sm:text-lg"
            alt="logo"
          >
            User5522
          </button>
        </a>
      </div>
      <div class="flex w-1/2 justify-end">
        <a href="/projects" class="text-white">
          <button
            class="rounded-lg p-2 text-base font-medium duration-200 hover:scale-110 hover:bg-dark_light active:scale-90 sm:text-lg"
          >
            Projects
          </button>
        </a>
        <a href="/blog" class="text-white">
          <button
            class="rounded-lg p-2 text-base font-medium duration-200 hover:scale-110 hover:bg-dark_light active:scale-90 sm:text-lg"
          >
            Blog
          </button>
        </a>
        <a href="/about" class="text-white">
          <button
            class="rounded-lg p-2 text-base font-medium duration-200 hover:scale-110 hover:bg-dark_light active:scale-90 sm:text-lg"
          >
            About
          </button>
        </a>
      </div>
    </div>
  </div>
</div>
